name: dating_app
description: "Dating app primitive simulator."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  location_finder:
    path: lib/location_finder

  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  random_name_generator: ^1.3.0
  english_words: ^4.0.0
  provider: ^6.0.0
  geolocator: ^12.0.0
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  network_image_mock: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - lib/location_finder/assets/style/map/classic_dark.json
    - lib/location_finder/assets/style/map/black_pink.json
    - lib/location_finder/assets/style/map/silver_pink.json